services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    expose:
      - "5173"
    volumes:
      - "./frontend:/frontend"
  magazyn:
    build: ./magazyn
    ports:
      - "5174:5174"
    expose:
      - "5174"
    volumes:
      - "./magazyn:/magazyn"
